name: Node.js CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install
      working-directory: ./node-app

    - name: Run Test Suite
      run: npm test
      working-directory: ./node-app

  start-server:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install
      working-directory: ./node-app

    - name: Start Server
      run: node app.js &
      working-directory: ./node-app
